MODEL:
  MODEL_DIR: ../data/model
  MODEL_TYPE: 3Cnet
  MODEL_NAME: model_0
  TID_PATH: ../data/transcript_ids.txt
  MSA_DIR: ../data/msa_data

  DATA_PATH: ../data/sequence_data/clinvar_dataset.bin
  DATA_ID_PATH: ../data/sequence_data/clinvar_mut.npy
  DATA_SNVBOX: ../data/SNVBOX_features/clinvar_features.npy
  ADD_PATH: ../data/sequence_data/common_dataset.bin # none for no additional negatives
  ADD_ID_PATH: ../data/sequence_data/common_mut.npy
  ADD_SNVBOX: ../data/SNVBOX_features/common_features.npy
  ENSEMBLE_PATH: ../data/sequence_data/conservation_dataset.bin
  ENSEMBLE_ID_PATH: ../data/sequence_data/conservation_mut.npy
  ENSEMBLE_SNVBOX: ../data/SNVBOX_features/conservation_features.npy

  SAVE_EACH_EPOCH: [True]
  TEST_RATIO: [0.01]

HYPERS:
  EMB_SIZE: [16]
  RNN_SIZE: [64]
  CNN_SIZE: [64]
  FC_SIZE: [32]
  SNV_FC_SIZE: [32]
  BATCH_SIZE: [128]
  OPTIMIZER: ['rmsprop']
  VALUE: ['val_loss']
  EPOCH: [50]
  PATIENCE: [10]
  LEARNING_RATE: [0.001]
  DROPOUT: [0.5]

VALID:
  VALID_DATA_PATH: ../data/sequence_data/clinvar_dataset.bin
  VALID_ID_PATH: ../data/sequence_data/clinvar_mut.npy
  VALID_SNVBOX: ../data/SNVBOX_features/clinvar_features.npy
  USE_TEST_ID: [True] # False uses all the data in VALID_DATA_PATH
  VALID_NAME: internal_clinvar
  VALID_METRICS: ['accuracy', 'roc_auc', 'pr_auc'] # give a blank list to skip evaluation. 'accuracy', 'roc_auc', 'pr_auc'
  VALID_TYPE: single
  MODEL_NUM: [] # model epoch for test
