DATA_DIR: ../data

DATA_FORMAT:
  SEQ_LEN: 201
  MUT_THRESHOLD: 0.5

BUILD:
  VARIANT_PATH: variant_data/patient_data.txt
  REFSEQ_PATH: transcript_seq.csv
  DATASET_PATH: sequence_data/patient_dataset.bin
  MUT_PATH: sequence_data/patient_mut.npy

VARIANT:
  DATASET_PATH: sequence_data/patient_dataset.bin
  MUT_PATH: sequence_data/patient_mut.npy
  VARIANT_PATH: variant_data/patient_variants.txt

MERGE:
  DATA_PATH_LIST: ['sequence_data/clinvar_dataset.bin', 'sequence_data/truncated_dataset.bin']
  MUT_PATH_LIST: ['sequence_data/clinvar_mut.npy', 'sequence_data/truncated_mut.npy']
  SNV_PATH_LIST: ['SNVBOX_features/clinvar_features.npy', 'none'] # 'none' for zero-padding
  MERGED_DATA: sequence_data/nonsynonymous_dataset.bin
  MERGED_MUT: sequence_data/nonsynonymous_mut.npy
  MERGED_SNV: SNVBOX_features/nonsynonymous_features.npy
